#!/bin/bash

EXPORT_FILE="$SNAP_COMMON/exports"
IFS=$'\n'

# Only one address for line is allowed
for line in $(cat "$EXPORT_FILE"); do
   FOLDER=$(echo $line  | awk '{ print $1 }')
   ADDRESS=$(echo $line | awk '{ print $2 }' | cut -f1 -d'(')
   OPTIONS=$(echo $line | awk -F'(' '{ print $2 }' | cut -f1 -d')')
   sudo snap run nfs-utils.export-fs -i -o $OPTIONS $ADDRESS:$FOLDER
   echo "Exporting $FOLDER to $ADDRESS with this options: $OPTIONS"
done
