name: nfs-server
version: 1.3.4
base: core18
summary: Network filesystems kernel server
#architectures: [armhf,amd64]
grade: stable
confinement: devmode ## exportfs required devmode or classic (need access to /proc/fs/nfsd directory)
description: |
   Network filesystems kernel server snap

apps:
  rpcbind:
    command: rpcbind -f
    #daemon: simple
    plugs: [network, network-bind]
    #sockets:
    #  rpcbind:
    #    listen-stream: 0.0.0.0:111

  export-fs:
    command: exportfs
    plugs: [home, removable-media, network, network-bind]

  export-all:
    command: export-all
    #daemon: simple
    plugs: [home, removable-media, network, network-bind]
    #stop-command: rpc.nfsd 0
    #post-stop-command: exportfs -au

parts:
  libtirpc:
    plugin: autotools
    source: git://git.linux-nfs.org/projects/steved/libtirpc.git
    source-type: git
    source-tag: libtirpc-0-2-5
    source-depth: 1
    configflags:
      - --prefix=/
      - --sysconfdir=/var/snap/nfs-server/common/config
      - --disable-gssapi

    override-pull: |
      snapcraftctl pull
      # Force new path for /etc/netconfig
      patch -p1 < ../../../files/netconfig.patch

    prime:
      - -include
      - -share

  rpcbind:
    plugin: autotools
    source: git://git.linux-nfs.org/projects/steved/rpcbind.git
    source-type: git
    source-tag: rpcbind-0_2_3
    source-depth: 1
    after: [ libtirpc ]
    configflags:
      - --prefix=/
      - --sysconfdir=/var/snap/nfs-server/common/config
      - --with-statedir=/var/snap/nfs-server/common/state

    build-packages:
      - libsystemd-dev

    prime:
      - -etc
      - -share
      - -usr/share

  nfs-utils:
    plugin: autotools
    source: git://git.linux-nfs.org/projects/steved/nfs-utils.git
    source-type: git
    source-tag: nfs-utils-2-3-3
    source-depth: 1
    after: [ rpcbind ]
    configflags:
      - --prefix=/
      - --sysconfdir=/var/snap/nfs-server/common/config
      - --with-statedir=/var/snap/nfs-server/common/state
      - --disable-gss
      - --disable-mount

    build-packages:
      - libsqlite3-dev
      - libdevmapper-dev
      - libblkid-dev
      - libkeyutils-dev
      - libxml2-dev
      - libevent-dev

    stage-packages:
      - libsqlite3-0
      - libdevmapper1.02.1
      - libblkid1
      - libevent-2.1-6

    prime:
      - -etc
      - -include
      - -var
      - -share
      - -usr/share

  scripts:
    source: files/
    plugin: dump
    organize:
      export-all: bin/export-all
