name: nfs-server
version: 1.3.4
base: core18
summary: Network filesystems kernel server
#architectures: [armhf,amd64]
grade: stable
confinement: devmode ## exportfs required devmode or classic (need access to /proc/fs/nfsd directory)
description: |
   Network filesystems kernel server snap

apps:
  rpcbind:
    command: rpcbind -w -f
    plugs: [network, network-bind]

  export-fs:
    command: exportfs -i
    plugs: [home, removable-media, network, network-bind]

  export-all:
    command: export-all
    plugs: [home, removable-media, network, network-bind]

parts:
  nfs-utils:
    plugin: autotools
    source: git://git.linux-nfs.org/projects/steved/nfs-utils.git
    source-type: git
    source-tag: nfs-utils-2-3-3
    source-depth: 1
    configflags:
      - --prefix=/
      - --with-statedir=/var/snap/nfs-utils/common/state
      - --disable-gss
      - --disable-mount

    build-packages:
      - libtirpc-dev
      - libsqlite3-dev
      - libdevmapper-dev
      - libblkid-dev
      - libkeyutils-dev
      - libxml2-dev
      - libevent-dev

    stage-packages:
      - libtirpc1
      - libsqlite3-0
      - libdevmapper1.02.1
      - libblkid1
      - rpcbind
      - libevent-2.1-6

    stage:
      - -etc
      - -include
      - -var
      - -share
      - -usr/share
